// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Announcer: typeof import('./components/Announcer.vue')['default']
    BigHeader: typeof import('./components/BigHeader.vue')['default']
    BodyCopy: typeof import('./components/BodyCopy.vue')['default']
    BuyButton: typeof import('./components/BuyButton.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Intro: typeof import('./components/Intro.vue')['default']
    LanguageSwitcher: typeof import('./components/examples/LanguageSwitcher.vue')['default']
    MediumHeader: typeof import('./components/MediumHeader.vue')['default']
    MicrositeBanner: typeof import('./components/MicrositeBanner.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavOptions: typeof import('./components/NavOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkipToContentLink: typeof import('./components/SkipToContentLink.vue')['default']
    SlideOutModal: typeof import('./components/SlideOutModal.vue')['default']
    SmallCopy: typeof import('./components/SmallCopy.vue')['default']
    SmallHeader: typeof import('./components/SmallHeader.vue')['default']
    StyledLink: typeof import('./components/StyledLink.vue')['default']
    Subheader: typeof import('./components/Subheader.vue')['default']
    VideoBackground: typeof import('./components/VideoBackground.vue')['default']
  }
}
